### ISSUE TITLE
Can mobile drones calculate world coordinates？

### ISSUE THREAD

**Issue by freefer** [rodolfoap/screen2world-k#2]
It seems that the world coordinates are calculated based on the image corresponding to a fixed camera. How to calculate the world coordinates for the selected points in the image transmitted from a moving unmanned image

**Comment by rodolfoap** [comment]
Coordinates are calculated using mathematical operations that correlate screen points with ground points. If the camera moves, the problem is to relocate the points on the screen.

For simple movements, there are opencv functions that allow detecting key elements on the screen, so to find screen points, recalculate the matrix and get the position.

For complex movements, I see such strategy too complex. A possible solution is to get the position (x,y,h coordinates) and orientation (p,t,z) by means of cellphone sensors, and then, calculate the transformation matrix.
